apiVersion: v1
kind: Service
metadata:
  name: course-app-service
  namespace: go-dev
spec:
  selector:
    app: course-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
