app_name: course-app-dev
app_env: docker
server_port: 8080

database:
  host: host.containers.internal  #used dns internal podman. because postgres not run via  compose (slirp4netns)
  port: 5432
  user: myuser
  pass: mypassword
  name: mydb
  sslmode: disable

log:
  level: debug
